### ISSUE TITLE
(Twoslash) Bug: Default style settings reference Astro Starlight theme tokens

### ISSUE THREAD

**Issue by IMax153** [MatthiesenXYZ/EC-Plugins#30]
**Describe the bug**

In the `styles.ts`, there is a reference to an Astro Starlight theme token:

https://github.com/MatthiesenXYZ/EC-Plugins/blob/df331035cddd6a46928b0fb43715b8b49b5ca0de/packages/twoslash/src/styles.ts#L398

This variable is unset in projects that may use `expressive-code-twoslash` but not Astro Starlight.

**To Reproduce**

1. Open the `styles.ts` file and scroll to line 398.

**Expected behavior**

This design token should be set to something valid and configurable, preferably with the same behavior as the Starlight token, which switches between plain white and plain black depending on the theme.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adammatthiesen** [comment]
Dang it... i thought i got rid of all those :sweat_smile: (that was for testing purposes before i had gotten most if not all the custom styles in place) will start working on it soon!
