### ISSUE TITLE
(Twoslash) Bug: Incorrect line-height for code snippets in Twoslash popups

### ISSUE THREAD

**Issue by IMax153** [MatthiesenXYZ/EC-Plugins#31]
**Describe the bug**

The line-height for code lines does not seem to be propagating into code snippets in the Twoslash popup container. See screenshot below.

On the Effect website, we've worked around this like so: https://github.com/Effect-TS/website/blob/411eb3ee01950f13f903404d48a15a7a5063bb44/content/src/styles/twoslash.css#L9

**To Reproduce**

1. Create a Twoslash code snippet on your site for a method with JSDocs that include code examples
2. Observe the code example in the rendered popup has smaller line-height than the parent

**Expected behavior**

Code snippets in the Twoslash popup should render with the same line-height as the parent code snippet.

**Screenshots**

![CleanShot 2024-12-05 at 14 42 33](https://github.com/user-attachments/assets/369e7f18-c99b-450d-80d2-66e54829241f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adammatthiesen** [comment]
yup... this is why i hate CSS... will resolve! (might also adopt your overrides from that CSS file all together...)
