### ISSUE TITLE
Failed to resolve style setting '...' for theme '...'

### ISSUE THREAD

**Issue by AndreyYolkin** [MatthiesenXYZ/EC-Plugins#6]
Hey! with the commit d629672ccb62986bccc016b853abdf72bb35c4f4 we can use advanced style options, provided by theme. However, some tokens might be missed in theme definition and that causes issues with dev/prod builds.

## Error case

Radashi uses `github-dark-dimmed` theme, for example. When trying to run the updated plugin, this error occurred:

```
Failed to resolve style setting 'twoSlash.completionBoxBackground' for theme 'github-dark-dimmed': 
The resolved value was undefined. This could be caused by your plugins or styleOverrides.
```

## Reproduction

To reproduce the bug, tweak your playground adding `github-dark-dimmed` as theme:

```ts
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import ectwoslash from "expressive-code-twoslash";

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: "Starlight",
			expressiveCode: {
				themes: ['github-dark-dimmed'],
				plugins: [ectwoslash()],
			},
		}),
	],
});
```

And run `playground:dev`. Here you go!

## Possible solutions

I suppose we are unable to test each theme presented, so I suggest to add extra fallbacks for defaults. Optionally plugin can warn if some color is missing in theme and ask to provide it manually

**Comment by Adammatthiesen** [comment]
Yeah sorry, haven't gotten all the CSS done yet... (Its a decent amount...) This issue is being caused by one or more possible tokens not having a value they usually should have.  You can also override these options using the example below:

```ts
expressiveCode: {
  themes: [ /* ... */ ],
  plugins: [ectwoslash()]
  styleOverrides: {
    twoSlash: {
      // You can then insert any of the tokens from the link here: (in your case: )
      completionBoxBackground: '#hex'
    },
  },
}
```
Link to tokens: https://github.com/MatthiesenXYZ/EC-Plugins/blob/fa42934d4031285ec1c7734a04eb9a0ce08a4a84/packages/twoslash/src/styles.ts#L29-L67

I am about to resume working on this again, i will note part of the issue at hand, is the fact that ExpressiveCode does not just support Shiki themes, but it actually supports full VSCode themes that do actually include a good chunk of these extra tokens...

> Optionally plugin can warn if some color is missing in theme and ask to provide it manually

From the plugin perspective i don't really get access to check to see if these values exist, hence why EC is the one telling the user, and thankfully there is an option for overrides that does exist.

**Comment by Adammatthiesen** [comment]
i've started work on this, feel free to test out the PR using the pkg.pr.new feature https://github.com/MatthiesenXYZ/EC-Plugins/pull/7#issuecomment-2466537473 if i have not released the update when you see this

**Comment by Adammatthiesen** [comment]
Just put out a new release `0.1.5` let me know if that resolves the issue!

**Comment by AndreyYolkin** [comment]
![tg_image_669649545](https://github.com/user-attachments/assets/ed39dffb-99a8-4bba-9669-84d60e44965e)

Sorry to bother you, but I still get this error even in repo's playground itself. (with 20.x node I got the same result, so it doesn't affect the issue)

**Comment by Adammatthiesen** [comment]
> ![tg_image_669649545](https://private-user-images.githubusercontent.com/11289484/384694208-ed39dffb-99a8-4bba-9669-84d60e44965e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTEzNjcsIm5iZiI6MTczMTI1MTA2NywicGF0aCI6Ii8xMTI4OTQ4NC8zODQ2OTQyMDgtZWQzOWRmZmItOTlhOC00YmJhLTk2NjktODRkNjBlNDQ5NjVlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjIyZWZlMDJjMGEzOThiNWEwYzEyMGVkMTFkNzMzOWFiM2UzOTMzMTQ4ZGZiYzMwN2IzOWE2MzAzMjAwZjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4yot1OpsJ6EdFoGiUmV-O6Rw6UeR_GBCihljE7C8P2M)
> 
> Sorry to bother you, but I still get this error even in repo's playground itself. (with 20.x node I got the same result, so it doesn't affect the issue)

fix incoming, my bad.  thought i could use references to my own vars in that location... apparently i can not :sweat_smile: 
https://github.com/MatthiesenXYZ/EC-Plugins/pull/10

**Comment by AndreyYolkin** [comment]
With the latest update I can confirm the issue is 100% resolved. Great job!
